package com.kang.model;

// Generated 2012-12-26 9:59:48 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StoreBraLink generated by hbm2java
 */
@Entity
@Table(name = "store_bra_link", schema = "dbo", catalog = "supCRM")
public class StoreBraLink implements java.io.Serializable {

	private int hzId;
	private SupStore supStore;
	private SupBrand supBrand;
	private Integer saleQty;
	private Double saleAmt;
	private Integer menQty;
	private Double menAmt;
	private Integer stockQty;
	private Integer couQty;
	private String linkBz;
	private Date saleDate;

	public StoreBraLink() {
	}

	public StoreBraLink(int hzId) {
		this.hzId = hzId;
	}

	public StoreBraLink(int hzId, SupStore supStore, SupBrand supBrand,
			Integer saleQty, Double saleAmt, Integer menQty, Double menAmt,
			Integer stockQty, Integer couQty, String linkBz, Date saleDate) {
		this.hzId = hzId;
		this.supStore = supStore;
		this.supBrand = supBrand;
		this.saleQty = saleQty;
		this.saleAmt = saleAmt;
		this.menQty = menQty;
		this.menAmt = menAmt;
		this.stockQty = stockQty;
		this.couQty = couQty;
		this.linkBz = linkBz;
		this.saleDate = saleDate;
	}

	@Id
	@Column(name = "hzId", unique = true, nullable = false)
	public int getHzId() {
		return this.hzId;
	}

	public void setHzId(int hzId) {
		this.hzId = hzId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storeId")
	public SupStore getSupStore() {
		return this.supStore;
	}

	public void setSupStore(SupStore supStore) {
		this.supStore = supStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brandId")
	public SupBrand getSupBrand() {
		return this.supBrand;
	}

	public void setSupBrand(SupBrand supBrand) {
		this.supBrand = supBrand;
	}

	@Column(name = "saleQty")
	public Integer getSaleQty() {
		return this.saleQty;
	}

	public void setSaleQty(Integer saleQty) {
		this.saleQty = saleQty;
	}

	@Column(name = "saleAmt", precision = 53, scale = 0)
	public Double getSaleAmt() {
		return this.saleAmt;
	}

	public void setSaleAmt(Double saleAmt) {
		this.saleAmt = saleAmt;
	}

	@Column(name = "menQty")
	public Integer getMenQty() {
		return this.menQty;
	}

	public void setMenQty(Integer menQty) {
		this.menQty = menQty;
	}

	@Column(name = "menAmt", precision = 53, scale = 0)
	public Double getMenAmt() {
		return this.menAmt;
	}

	public void setMenAmt(Double menAmt) {
		this.menAmt = menAmt;
	}

	@Column(name = "stockQty")
	public Integer getStockQty() {
		return this.stockQty;
	}

	public void setStockQty(Integer stockQty) {
		this.stockQty = stockQty;
	}

	@Column(name = "couQty")
	public Integer getCouQty() {
		return this.couQty;
	}

	public void setCouQty(Integer couQty) {
		this.couQty = couQty;
	}

	@Column(name = "linkBZ")
	public String getLinkBz() {
		return this.linkBz;
	}

	public void setLinkBz(String linkBz) {
		this.linkBz = linkBz;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "saleDate", length = 23)
	public Date getSaleDate() {
		return this.saleDate;
	}

	public void setSaleDate(Date saleDate) {
		this.saleDate = saleDate;
	}

}
