package com.kang.model;

// Generated 2012-12-26 9:59:48 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SupPlu generated by hbm2java
 */
@Entity
@Table(name = "supPlu", schema = "dbo", catalog = "supCRM")
public class SupPlu implements java.io.Serializable {

	private int pluId;
	private SupBrand supBrand;
	private String pluNum;
	private String pluCode;
	private String pluName;
	private String pluNorms;
	private String pluBz;
	private Set<StorePluLink> storePluLinks = new HashSet<StorePluLink>(0);

	public SupPlu() {
	}

	public SupPlu(int pluId) {
		this.pluId = pluId;
	}

	public SupPlu(int pluId, SupBrand supBrand, String pluNum, String pluCode,
			String pluName, String pluNorms, String pluBz,
			Set<StorePluLink> storePluLinks) {
		super();
		this.pluId = pluId;
		this.supBrand = supBrand;
		this.pluNum = pluNum;
		this.pluCode = pluCode;
		this.pluName = pluName;
		this.pluNorms = pluNorms;
		this.pluBz = pluBz;
		this.storePluLinks = storePluLinks;
	}

	@Id
	@Column(name = "pluId", unique = true, nullable = false)
	public int getPluId() {
		return this.pluId;
	}

	public void setPluId(int pluId) {
		this.pluId = pluId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brandId")
	public SupBrand getSupBrand() {
		return this.supBrand;
	}

	public void setSupBrand(SupBrand supBrand) {
		this.supBrand = supBrand;
	}

	@Column(name = "pluNum")
	public String getPluNum() {
		return this.pluNum;
	}

	public void setPluNum(String pluNum) {
		this.pluNum = pluNum;
	}

	@Column(name = "pluCode")
	public String getPluCode() {
		return this.pluCode;
	}

	public void setPluCode(String pluCode) {
		this.pluCode = pluCode;
	}

	@Column(name = "pluName")
	public String getPluName() {
		return this.pluName;
	}

	public void setPluName(String pluName) {
		this.pluName = pluName;
	}

	@Column(name = "pluNorms")
	public String getPluNorms() {
		return this.pluNorms;
	}

	public void setPluNorms(String pluNorms) {
		this.pluNorms = pluNorms;
	}

	@Column(name = "pluBZ")
	public String getPluBz() {
		return this.pluBz;
	}

	public void setPluBz(String pluBz) {
		this.pluBz = pluBz;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supPlu")
	public Set<StorePluLink> getStorePluLinks() {
		return this.storePluLinks;
	}

	public void setStorePluLinks(Set<StorePluLink> storePluLinks) {
		this.storePluLinks = storePluLinks;
	}

}
