package com.kang.model;

// Generated 2012-12-26 9:59:48 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SupStore generated by hbm2java
 */
@Entity
@Table(name = "supStore", schema = "dbo", catalog = "supCRM")
public class SupStore implements java.io.Serializable {

	private int storeId;
	private SupArea supArea;
	private String storeNum;
	private String storeName;
	private String storeBz;
	private String storeStatus;
	private Set<StorePluLink> storePluLinks = new HashSet<StorePluLink>(0);
	private Set<StoreBraLink> storeBraLinks = new HashSet<StoreBraLink>(0);

	public SupStore() {
	}

	public SupStore(int storeId) {
		this.storeId = storeId;
	}

	public SupStore(int storeId, SupArea supArea, String storeNum,
			String storeName, String storeBz,
			String storeStatus, Set storePluLinks, Set storeBraLinks) {
		this.storeId = storeId;
		this.supArea = supArea;
		this.storeNum = storeNum;
		this.storeName = storeName;
		this.storeBz = storeBz;
		this.storeStatus = storeStatus;
		this.storePluLinks = storePluLinks;
		this.storeBraLinks = storeBraLinks;
	}

	@Id
	@Column(name = "storeId", unique = true, nullable = false)
	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "areaId")
	public SupArea getSupArea() {
		return this.supArea;
	}

	public void setSupArea(SupArea supArea) {
		this.supArea = supArea;
	}

	@Column(name = "storeNum")
	public String getStoreNum() {
		return this.storeNum;
	}

	public void setStoreNum(String storeNum) {
		this.storeNum = storeNum;
	}

	@Column(name = "storeName")
	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@Column(name = "storeBZ")
	public String getStoreBz() {
		return this.storeBz;
	}

	public void setStoreBz(String storeBz) {
		this.storeBz = storeBz;
	}

	@Column(name = "storeStatus")
	public String getStoreStatus() {
		return this.storeStatus;
	}

	public void setStoreStatus(String storeStatus) {
		this.storeStatus = storeStatus;
	}
	
	
	public void setStorePluLinks(Set<StorePluLink> storePluLinks) {
		this.storePluLinks = storePluLinks;
	}

	public void setStoreBraLinks(Set<StoreBraLink> storeBraLinks) {
		this.storeBraLinks = storeBraLinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supStore")
	public Set<StorePluLink> getStorePluLinks() {
		return this.storePluLinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supStore")
	public Set<StoreBraLink> getStoreBraLinks() {
		return this.storeBraLinks;
	}

	

}
