package com.kang.model;

// Generated 2012-12-26 9:59:48 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsrAreaBrandLink generated by hbm2java
 */
@Entity
@Table(name = "usr_area_brand_link", schema = "dbo", catalog = "supCRM")
public class UsrAreaBrandLink implements java.io.Serializable {

	private int linkId;
	private SupArea supArea;
	private MyUsr myUsr;
	private SupBrand supBrand;
	private Date startTime;
	private Date endTime;
	private java.lang.String linkBz;
	private String linkStatus;

	public UsrAreaBrandLink() {
	}

	public UsrAreaBrandLink(int linkId) {
		this.linkId = linkId;
	}

	public UsrAreaBrandLink(int linkId, SupArea supArea, MyUsr myUsr,
			SupBrand supBrand, Date startTime, Date endTime,
			String linkBz, String linkStatus) {
		this.linkId = linkId;
		this.supArea = supArea;
		this.myUsr = myUsr;
		this.supBrand = supBrand;
		this.startTime = startTime;
		this.endTime = endTime;
		this.linkBz = linkBz;
		this.linkStatus = linkStatus;
	}

	@Id
	@Column(name = "linkId", unique = true, nullable = false)
	public int getLinkId() {
		return this.linkId;
	}

	public void setLinkId(int linkId) {
		this.linkId = linkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "areaId")
	public SupArea getSupArea() {
		return this.supArea;
	}

	public void setSupArea(SupArea supArea) {
		this.supArea = supArea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usrId")
	public MyUsr getMyUsr() {
		return this.myUsr;
	}

	public void setMyUsr(MyUsr myUsr) {
		this.myUsr = myUsr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brandId")
	public SupBrand getSupBrand() {
		return this.supBrand;
	}

	public void setSupBrand(SupBrand supBrand) {
		this.supBrand = supBrand;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startTime", length = 23)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endTime", length = 23)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "linkBZ")
	public String getLinkBz() {
		return this.linkBz;
	}

	public void setLinkBz(String linkBz) {
		this.linkBz = linkBz;
	}

	@Column(name = "linkStatus")
	public String getLinkStatus() {
		return this.linkStatus;
	}

	public void setLinkStatus(String linkStatus) {
		this.linkStatus = linkStatus;
	}

}
