package com.kang.model;

// Generated 2012-12-26 9:59:48 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SupBrand generated by hbm2java
 */
@Entity
@Table(name = "supBrand", schema = "dbo", catalog = "supCRM")
public class SupBrand implements java.io.Serializable {

	private int brandId;
	private String brandNum;
	private String brandName;
	private String brandBz;
	private String brandStatus;
	private Set<SupPlu> supPlus = new HashSet<SupPlu>(0);
	private Set<UsrAreaBrandLink> usrAreaBrandLinks = new HashSet<UsrAreaBrandLink>(0);
	private Set<StoreBraLink> storeBraLinks = new HashSet<StoreBraLink>(0);

	public SupBrand() {
	}

	public SupBrand(int brandId) {
		this.brandId = brandId;
	}

	public SupBrand(int brandId, String brandNum, String brandName,
			String brandBz, String brandStatus, Set<SupPlu> supPlus,
			Set<UsrAreaBrandLink> usrAreaBrandLinks,
			Set<StoreBraLink> storeBraLinks) {
		super();
		this.brandId = brandId;
		this.brandNum = brandNum;
		this.brandName = brandName;
		this.brandBz = brandBz;
		this.brandStatus = brandStatus;
		this.supPlus = supPlus;
		this.usrAreaBrandLinks = usrAreaBrandLinks;
		this.storeBraLinks = storeBraLinks;
	}

	@Id
	@Column(name = "brandId", unique = true, nullable = false)
	public int getBrandId() {
		return this.brandId;
	}

	public void setBrandId(int brandId) {
		this.brandId = brandId;
	}

	@Column(name = "brandNum")
	public String getBrandNum() {
		return this.brandNum;
	}

	public void setBrandNum(String brandNum) {
		this.brandNum = brandNum;
	}

	@Column(name = "brandName")
	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	@Column(name = "brandBZ")
	public String getBrandBz() {
		return this.brandBz;
	}

	public void setBrandBz(String brandBz) {
		this.brandBz = brandBz;
	}

	@Column(name = "brandStatus")
	public String getBrandStatus() {
		return this.brandStatus;
	}

	public void setBrandStatus(String brandStatus) {
		this.brandStatus = brandStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supBrand")
	public Set<SupPlu> getSupPlus() {
		return this.supPlus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supBrand")
	public Set<UsrAreaBrandLink> getUsrAreaBrandLinks() {
		return this.usrAreaBrandLinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supBrand")
	public Set<StoreBraLink> getStoreBraLinks() {
		return this.storeBraLinks;
	}

	public void setSupPlus(Set<SupPlu> supPlus) {
		this.supPlus = supPlus;
	}

	public void setUsrAreaBrandLinks(Set<UsrAreaBrandLink> usrAreaBrandLinks) {
		this.usrAreaBrandLinks = usrAreaBrandLinks;
	}

	public void setStoreBraLinks(Set<StoreBraLink> storeBraLinks) {
		this.storeBraLinks = storeBraLinks;
	}

	
	
	
	
}
