package com.kang.model;

// Generated 2012-10-21 14:03:41 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysUsers generated by hbm2java
 */
@Entity
@Table(name = "sys_users", schema = "dbo", catalog = "jbpm")
public class SysUsers implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "usrid", unique = true, nullable = false)
	private int usrid;
	
	private String usrname;
	private String usrpwd;
	private Integer usrtype;
	private Integer usrmgr;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUsers")
	private Set<TReimapp> TReimapps = new HashSet<TReimapp>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUsers")
	private Set<TReim> TReims = new HashSet<TReim>(0);

	public SysUsers() {
	}

	public SysUsers(int usrid) {
		this.usrid = usrid;
	}

	public SysUsers(int usrid, String usrname, String usrpwd, Integer usrtype,
			Integer usrmgr, Set<TReimapp> TReimapps, Set<TReim> TReims) {
		this.usrid = usrid;
		this.usrname = usrname;
		this.usrpwd = usrpwd;
		this.usrtype = usrtype;
		this.usrmgr = usrmgr;
		this.TReimapps = TReimapps;
		this.TReims = TReims;
	}

	
	public int getUsrid() {
		return this.usrid;
	}

	public void setUsrid(int usrid) {
		this.usrid = usrid;
	}

	@Column(name = "usrname", length = 20)
	public String getUsrname() {
		return this.usrname;
	}

	public void setUsrname(String usrname) {
		this.usrname = usrname;
	}

	@Column(name = "usrpwd", length = 20)
	public String getUsrpwd() {
		return this.usrpwd;
	}

	public void setUsrpwd(String usrpwd) {
		this.usrpwd = usrpwd;
	}

	@Column(name = "usrtype")
	public Integer getUsrtype() {
		return this.usrtype;
	}

	public void setUsrtype(Integer usrtype) {
		this.usrtype = usrtype;
	}

	@Column(name = "usrmgr")
	public Integer getUsrmgr() {
		return this.usrmgr;
	}

	public void setUsrmgr(Integer usrmgr) {
		this.usrmgr = usrmgr;
	}

	
	public Set<TReimapp> getTReimapps() {
		return this.TReimapps;
	}

	public void setTReimapps(Set<TReimapp> TReimapps) {
		this.TReimapps = TReimapps;
	}

	
	public Set<TReim> getTReims() {
		return this.TReims;
	}

	public void setTReims(Set<TReim> TReims) {
		this.TReims = TReims;
	}

}
