package com.kang.model;

// Generated 2012-10-21 14:03:41 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TReimapp generated by hbm2java
 */
@Entity
@Table(name = "t_reimapp", schema = "dbo", catalog = "jbpm")
public class TReimapp implements java.io.Serializable {

	private int appId;
	private TReim TReim;
	private SysUsers sysUsers;
	private String apptext;
	private String appdesc;
	private Date appdate;

	public TReimapp() {
	}

	public TReimapp(int appId) {
		this.appId = appId;
	}

	public TReimapp(int appId, TReim TReim, SysUsers sysUsers, String apptext,
			String appdesc, Date appdate) {
		this.appId = appId;
		this.TReim = TReim;
		this.sysUsers = sysUsers;
		this.apptext = apptext;
		this.appdesc = appdesc;
		this.appdate = appdate;
	}

	@Id
	@GeneratedValue
	@Column(name = "app_id", unique = true, nullable = false)
	public int getAppId() {
		return this.appId;
	}

	public void setAppId(int appId) {
		this.appId = appId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rmid")
	public TReim getTReim() {
		return this.TReim;
	}

	public void setTReim(TReim TReim) {
		this.TReim = TReim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usrid")
	public SysUsers getSysUsers() {
		return this.sysUsers;
	}

	public void setSysUsers(SysUsers sysUsers) {
		this.sysUsers = sysUsers;
	}

	@Column(name = "apptext", length = 30)
	public String getApptext() {
		return this.apptext;
	}

	public void setApptext(String apptext) {
		this.apptext = apptext;
	}

	@Column(name = "appdesc", length = 100)
	public String getAppdesc() {
		return this.appdesc;
	}

	public void setAppdesc(String appdesc) {
		this.appdesc = appdesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "appdate", length = 23)
	public Date getAppdate() {
		return this.appdate;
	}

	public void setAppdate(Date appdate) {
		this.appdate = appdate;
	}

}
