package com.kang.model;

// Generated 2012-10-21 14:03:41 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TReim generated by hbm2java
 */
@Entity
@Table(name = "t_reim", schema = "dbo", catalog = "jbpm")
public class TReim implements java.io.Serializable {

	private int rmid;
	private SysUsers sysUsers;
	private String rmname;
	private String rmdesc;
	private Date rmdate;
	private Set<TReimitm> TReimitms = new HashSet<TReimitm>(0);
	private Set<TReimapp> TReimapps = new HashSet<TReimapp>(0);

	public TReim() {
	}

	public TReim(int rmid) {
		this.rmid = rmid;
	}

	public TReim(int rmid, SysUsers sysUsers, String rmname, String rmdesc,
			Date rmdate, Set TReimitms, Set TReimapps) {
		this.rmid = rmid;
		this.sysUsers = sysUsers;
		this.rmname = rmname;
		this.rmdesc = rmdesc;
		this.rmdate = rmdate;
		this.TReimitms = TReimitms;
		this.TReimapps = TReimapps;
	}

	@Id
	@GeneratedValue
	@Column(name = "rmid", unique = true, nullable = false)
	public int getRmid() {
		return this.rmid;
	}

	public void setRmid(int rmid) {
		this.rmid = rmid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usrid")
	public SysUsers getSysUsers() {
		return this.sysUsers;
	}

	public void setSysUsers(SysUsers sysUsers) {
		this.sysUsers = sysUsers;
	}

	@Column(name = "rmname", length = 50)
	public String getRmname() {
		return this.rmname;
	}

	public void setRmname(String rmname) {
		this.rmname = rmname;
	}

	@Column(name = "rmdesc", length = 200)
	public String getRmdesc() {
		return this.rmdesc;
	}

	public void setRmdesc(String rmdesc) {
		this.rmdesc = rmdesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rmdate", length = 23)
	public Date getRmdate() {
		return this.rmdate;
	}

	public void setRmdate(Date rmdate) {
		this.rmdate = rmdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TReim")
	public Set<TReimitm> getTReimitms() {
		return this.TReimitms;
	}

	public void setTReimitms(Set<TReimitm> TReimitms) {
		this.TReimitms = TReimitms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TReim")
	public Set<TReimapp> getTReimapps() {
		return this.TReimapps;
	}

	public void setTReimapps(Set<TReimapp> TReimapps) {
		this.TReimapps = TReimapps;
	}

}
