package com.kang.model;

// Generated 2012-10-21 14:03:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TReimitm generated by hbm2java
 */
@Entity
@Table(name = "t_reimitm", schema = "dbo", catalog = "jbpm")
public class TReimitm implements java.io.Serializable {

	private int rmitmid;
	private TReim TReim;
	private String rmitmname;
	private BigDecimal rmitmcost;
	private String rmitmdesc;

	public TReimitm() {
	}

	public TReimitm(int rmitmid) {
		this.rmitmid = rmitmid;
	}

	public TReimitm(int rmitmid, TReim TReim, String rmitmname,
			BigDecimal rmitmcost, String rmitmdesc) {
		this.rmitmid = rmitmid;
		this.TReim = TReim;
		this.rmitmname = rmitmname;
		this.rmitmcost = rmitmcost;
		this.rmitmdesc = rmitmdesc;
	}

	@Id
	@GeneratedValue
	@Column(name = "rmitmid", unique = true, nullable = false)
	public int getRmitmid() {
		return this.rmitmid;
	}

	public void setRmitmid(int rmitmid) {
		this.rmitmid = rmitmid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rmid")
	public TReim getTReim() {
		return this.TReim;
	}

	public void setTReim(TReim TReim) {
		this.TReim = TReim;
	}

	@Column(name = "rmitmname", length = 50)
	public String getRmitmname() {
		return this.rmitmname;
	}

	public void setRmitmname(String rmitmname) {
		this.rmitmname = rmitmname;
	}

	@Column(name = "rmitmcost", precision = 12)
	public BigDecimal getRmitmcost() {
		return this.rmitmcost;
	}

	public void setRmitmcost(BigDecimal rmitmcost) {
		this.rmitmcost = rmitmcost;
	}

	@Column(name = "rmitmdesc", length = 100)
	public String getRmitmdesc() {
		return this.rmitmdesc;
	}

	public void setRmitmdesc(String rmitmdesc) {
		this.rmitmdesc = rmitmdesc;
	}

}
