USE [master]
GO
/****** Object:  Database [springJDBC]    Script Date: 2012/11/13 20:50:51 ******/
CREATE DATABASE [springJDBC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'springJDBC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\springJDBC.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'springJDBC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\springJDBC_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [springJDBC] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [springJDBC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [springJDBC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [springJDBC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [springJDBC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [springJDBC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [springJDBC] SET ARITHABORT OFF 
GO
ALTER DATABASE [springJDBC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [springJDBC] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [springJDBC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [springJDBC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [springJDBC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [springJDBC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [springJDBC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [springJDBC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [springJDBC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [springJDBC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [springJDBC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [springJDBC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [springJDBC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [springJDBC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [springJDBC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [springJDBC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [springJDBC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [springJDBC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [springJDBC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [springJDBC] SET  MULTI_USER 
GO
ALTER DATABASE [springJDBC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [springJDBC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [springJDBC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [springJDBC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [springJDBC]
GO
/****** Object:  StoredProcedure [dbo].[springProc]    Script Date: 2012/11/13 20:50:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create proc [dbo].[springProc]
			@userId int,
			@userName varchar(40) output,
			@usrPwd varchar(40) out

as 
	
	begin 
		
		select @userName  = userName,@usrPwd = usrPwd from t_user where userId = @userId;

	end


GO
/****** Object:  Table [dbo].[t_user]    Script Date: 2012/11/13 20:50:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[t_user](
	[userId] [int] IDENTITY(1,1) NOT NULL,
	[userName] [varchar](40) NULL,
	[usrPwd] [varchar](40) NULL,
PRIMARY KEY CLUSTERED 
(
	[userId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[testUser]    Script Date: 2012/11/13 20:50:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[testUser](
	[userId] [int] IDENTITY(1,1) NOT NULL,
	[userName] [nvarchar](40) NULL,
	[userPwd] [nvarchar](40) NULL,
PRIMARY KEY CLUSTERED 
(
	[userId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [springJDBC] SET  READ_WRITE 
GO
